/* eslint-disable no-unused-vars */
import Login from './modules/invitado/Login'
import Home from './modules/invitado/Home'
import Register from './modules/invitado/Register'
import RecuperarContrasena from './modules/invitado/RecuperarContrasena'
import RestablecerContrasena from './modules/invitado/RestablecerContrasena'
import PaginaNoEncontrada from './modules/invitado/PaginaNoEncontrada'
import Confirmacion from './modules/invitado/Confirmacion'

import DashboardAprendiz from './modules/aprendiz/DashboardAprendiz'
import MisProyectos from './modules/aprendiz/MisProyectos'
import NuevoProyecto from './modules/aprendiz/NuevoProyecto'
import MensajesAprendiz from './modules/aprendiz/MensajesAprendiz'
import NuevoMensajeAprendiz from './modules/aprendiz/NuevoMensajeAprendiz'
import AlertasAprendiz from './modules/aprendiz/AlertasAprendiz'
import MiPerfil from './modules/aprendiz/MiPerfil'
import UnirseFicha from './modules/aprendiz/UnirseFicha'
import ReportarFallaAprendiz from './modules/aprendiz/ReportarFallaAprendiz'
import RegistrarAvances from './modules/aprendiz/RegistrarAvances'
import DetalleProyecto from './modules/aprendiz/DetalleProyecto'
import DetalleRevision from './modules/aprendiz/DetalleRevision'
import DetalleSimilitud from './modules/aprendiz/DetalleSimilitud'
import DetalleFicha from './modules/aprendiz/DetalleFicha'
import DirectorioFicha from './modules/aprendiz/DirectorioFicha'

import DashboardInstructor from './modules/instructor/DashboardInstructor'
import GestionarFichas from './modules/instructor/GestionarFichas'
import CrearFicha from './modules/instructor/CrearFicha'
import RevisionPropuestas from './modules/instructor/RevisionPropuestas'
import RevisionAvances from './modules/instructor/RevisionAvances'
import HistorialRevisiones from './modules/instructor/HistorialRevisiones'
import MensajesInstructor from './modules/instructor/MensajesInstructor'
import NuevoMensajeInstructor from './modules/instructor/NuevoMensajeInstructor'
import AlertasInstructor from './modules/instructor/AlertasInstructor'
import PerfilInstructor from './modules/instructor/PerfilInstructor'
import ReportarFallaInstructor from './modules/instructor/ReportarFallaInstructor'
import DetalleProyectoInstructor from './modules/instructor/DetalleProyectoInstructor'
import DetalleRevisionInstructor from './modules/instructor/DetalleRevisionInstructor'
import DetalleSimilitudInstructor from './modules/instructor/DetalleSimilitudInstructor'
import DetalleFichaInstructor from './modules/instructor/DetalleFichaInstructor'
import DirectorioFichaInstructor from './modules/instructor/DirectorioFichaInstructor'
import AnalizandoProyecto from './modules/instructor/AnalizandoProyecto'
import ResultadoAnalisis from './modules/instructor/ResultadoAnalisis'

import DashboardAdmin from './modules/admin/DashboardAdmin'
import GestionUsuarios from './modules/admin/GestionUsuarios'
import NuevoUsuario from './modules/admin/NuevoUsuario'
import Reportes from './modules/admin/Reportes'
import ReportesFallas from './modules/admin/ReportesFallas'
import DetalleReporte from './modules/admin/DetalleReporte'
import DetalleSimilitudAdmin from './modules/admin/DetalleSimilitudAdmin'
import DetalleProyectoAdmin from './modules/admin/DetalleProyectoAdmin'
import DetalleUsuario from './modules/admin/DetalleUsuario'

export default function App() {
  return (
    <DashboardAprendiz />
  )
}
